### ISSUE TITLE
Persisting the call data

### ISSUE THREAD

**Issue by ksubramanian2** [webdriverio-community/wdio-intercept-service#102]
Is there a way to persist the network calls after navigating to a new page?

I am doing  a network call in the 'beforeunload' event and I want to check this call.  But it is already in the new page and shows a count of zero.

**Comment by ksubramanian2** [comment]
Correction:  It is showing the earlier calls,  but not the call from the 'beforeunload',

I have not done setupInterceptor after the browser.url() for the new page. Do I need to?

**Comment by ksubramanian2** [comment]
In my test, if I use 
browser.execute(() => {
      window.dispatchEvent(new Event('beforeunload'));
    });
it shows the call made in the beforeunload event handler.

But, if I use browser.url() raising the beforeunload event indirectly, then it does not show the call made there.

**Comment by chmanie** [comment]
Calls are persisted in the sessionStorage. This storage is only good for the same website URL (maybe even subdomain, I'm not sure). So if the new page is on the same domain, it should work.
