### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-intercept-service#131]
Hey @chmanie  ,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

I was wondering if you would be interested moving this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by chmanie** [comment]
Hey @christian-bromann! Yes, I'd be very happy to move this project. I don't find much time maintaining it anymore so a few more eyes on it won't hurt.
I think it might be even broken at the moment with the current wdio version 7, but I'll look into that.

Let me know how you'd like to proceed!

**Comment by christian-bromann** [comment]
Awesome, please follow [this guide](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) and put `webdriverio-community` as new owner of this repository. We have sent you an invite to the org.

**Comment by chmanie** [comment]
It's moved!

**Comment by chmanie** [comment]
@christian-bromann I had CI integration with travis-ci. How would you like to handle this now? Are github actions available in this org?

**Comment by christian-bromann** [comment]
> Are github actions available in this org?

Yes, we should switch to GitHub Actions.
