### ISSUE TITLE
getRequests() is returning empty array

### ISSUE THREAD

**Issue by ariesranjan** [webdriverio-community/wdio-intercept-service#140]
browser.getRequests() is returning empty array. Below are the versions I am using:

WebdriverIO: 7.6.1
Node: 14.16.1
wdio-intercept-service: 4.1.6
Framework: Mocha
Browser: Chrome
Browser Version: 91

Below is the code snippet I am using:

```
fetchRequests(){
    browser.url('/');
    browser.setInterceptor();
    browser.pause(5000);
    browser.clickContinue();
    const requests = browser.getRequests();
    console.log(requests);
  }
```
Please help how to resolve this.

**Comment by 1MaJKeL1** [comment]
Unfortunately I have to confirm the same problem in the latest version of WDIO 
wdio.conf.js

services: [
    [
      "chromedriver",
      {
        logFileName: "wdio-chromedriver.log",
        outputDir: "Results/logs/driver",
        args: ["--silent", "--disable-logging", "--disable-infobars"],
      },
    ],
    ["intercept"],
  ],

packake.json
 "dependencies": {
    "wdio-chromedriver-service": "7.2.0",
    "inquirer": "8.1.2",

example code

  it("Intercept any request", function () {
    browser.url("https://webdriver.io");
    browser.setupInterceptor();
    browser.pause(wait);
    $("*=Get Started").click();
    browser.pause(wait);
    const request = browser.getRequests();
    console.log("Requests:", request);
  });

**Comment by ejames17** [comment]
i am able to capture request however I don't get all xhr request.

**Comment by mattdell** [comment]
Same here. Just returns `[]` when I know requests are being made. 😕

**Comment by ImBeCiliC** [comment]
I get all xhr request that are triggered after initialization but the fetch calls aren't catched at all. There is no testing for my Segment integration right now.

**Comment by tehhowch** [comment]
As of v4.2.0 you can request not-yet-completed requests to be returned in a call to `getRequests()`:
```js
const completedAndPending = browser.getRequests({ includePending: true });
const completedOnly = browser.getRequests();
const orderedByInitiationInsteadOfEnding = browser.getRequests({ orderBy: 'START' });
```

**Comment by christian-bromann** [comment]
Closing the issue then.

**Comment by MPSwift** [comment]
> ```js
> const completedAndPending = browser.getRequests({ includePending: true });
> const completedOnly = browser.getRequests();
> const orderedByInitiationInsteadOfEnding = browser.getRequests({ orderBy: 'START' });
> ```

Unfortunately that did not help to get the fetch calls and there were no pending requests. I still cannot catch the fetch calls but xhr requests.

**Comment by tehhowch** [comment]
> > ```js
> > const completedAndPending = browser.getRequests({ includePending: true });
> > const completedOnly = browser.getRequests();
> > const orderedByInitiationInsteadOfEnding = browser.getRequests({ orderBy: 'START' });
> > ```
> 
> Unfortunately that did not help to get the fetch calls and there were no pending requests. I still cannot catch the fetch calls but xhr requests.

Sounds like you should open a new issue and in that issue, provide significant details about the exact scenario occuring (server and browser), including what does and does not get captured and what the browser is doing while the requests are being made:

> Fetch? XmlHttpRequest? What browser? What protocol? How is the url set up (e.g. string, a `Url`, a `Request`, etc.)? What content-type of response did the server send? What cors modes are used? Etc.

If you can't supply this level of detail I don't think anyone can help you, unfortunately.

**Comment by SebastianFromSnapTravel** [comment]
Im getting the same issue. Basically, my browser is making API calls but only some are appearing in browser.getRequests. Oddly enough, when I run the test with the browser open, and open the network tab to see if the req is happening, the test passes (ie. the calls show up in broswer.getRequests()  - lol) but in any other case, its not detecting the api call.
