### ISSUE TITLE
Is there a way to run wdio-intercept-service without using wdio.conf.js and running it in standalone 

### ISSUE THREAD

**Issue by shandilyamaramraju** [webdriverio-community/wdio-intercept-service#141]

**Comment by christian-bromann** [comment]
@shandilyamaramraju you can use the [`mock`](https://webdriver.io/docs/api/browser/mock) to intercept requests. This command should also work outside of the wdio testrunner.

**Comment by shandilyamaramraju** [comment]
Hi Webdriverio-Community/Wdio-Intercept-Service,
I want to use intercept service but my test runner is cucumber js . I’m not
using wdio test runner . Could you please help me? Our use case is to grab
the response and response headers of the post payload.

Thanks,
Shandilya

**Comment by christian-bromann** [comment]
@shandilyamaramraju please see my answer above.

**Comment by shandilyamaramraju** [comment]
Hi Christian,
I don’t want to use mock and I don’t want to modify any request response. I
am looking for an example on how to use intercept service outside
wdio-test-runner. Please let me know.

**Comment by christian-bromann** [comment]
WebdriverIO doesn't allow services outside of the wdio testrunner.
