### ISSUE TITLE
Link in the Expect does not work

### ISSUE THREAD

**Issue by timestampx** [webdriverio-community/wdio-intercept-service#147]
https://webdriver.io/docs/api/expect-webdriverio/#tobechecked
open page with 404 error, when I click 'isSelected' 
<img width="1138" alt="Снимок экрана 2021-09-01 в 15 04 05" src="https://user-images.githubusercontent.com/5372340/131668331-e5e61ec3-39ab-4db0-9222-829167288c0a.png">

**Comment by christian-bromann** [comment]
Fixed with above commit.
