### ISSUE TITLE
Question: Can we use getRequest method with reqex as argument?

### ISSUE THREAD

**Issue by jasminhusadzic** [webdriverio-community/wdio-intercept-service#208]
I have situation where i need to intercept only certain request, and i don't know which index will be. Any suggestion in this case?

Thanks and regards

**Comment by tehhowch** [comment]
You cannot intercept only requests that match a particular predicate. If you use this library, all outgoing requests are instrumented and captured.

When you call `getRequests()` you will get all completed requests in a standard javascript array. You can then just filter that array by your predicate with normal JavaScript. E.g.

```js
const allRequests = await browser.getRequests({ includePending: true, orderBy: 'START' });
const theFirstStartedRequestOfInterest = allRequests.find((rq) => rq.method === 'GET' && /my-cool-regex/.test(rq.url));
// do stuff with theFirstStartedRequestOfInterest
```
