### ISSUE TITLE
[Version 4.2.2] browser.disableInterceptor() is not a function

### ISSUE THREAD

**Issue by chadbellangivelify** [webdriverio-community/wdio-intercept-service#418]
Is browser.disableInterceptor() only available for version 4.3.0?  When I try to use it I'm getting an error that it's not a function

**Comment by tehhowch** [comment]
> Is browser.disableInterceptor() only available for version 4.3.0? When I try to use it I'm getting an error that it's not a function

Correct: https://github.com/webdriverio-community/wdio-intercept-service/blob/v4.2.2/CHANGELOG.md
It was added in commit https://github.com/webdriverio-community/wdio-intercept-service/commit/48da3c849a24d5dece8317da3ff296b834777aca
