### ISSUE TITLE
browser.getRequests() hanging without @wdio/sync module

### ISSUE THREAD

**Issue by ksubramanian2** [webdriverio-community/wdio-intercept-service#419]
I have been using the intercept service for a couple of years and it has been working well for me.
I have now tried to update all the wdio dependencies and in the process, removed the @wdio/sync module from package.json as it was not supporting Node 16.  So, I had to update all the browser. calls to have an 'await'.
Now, the following call
    await browser.getRequests() 
never returns. 
I have the intercept service defined in the config and have called the setUpInterceptor() too.  Anything else I am missing?
Thanks for your help, in advance.
Krishna

**Comment by christian-bromann** [comment]
Hey @ksubramanian2 , thanks for filing an issue.

Do you have a reproducible example?

**Comment by ksubramanian2** [comment]
Thanks, @christian-bromann, for the quick response.  I do not have an example to share readily.  Our repo is in our intranet. 
I can put an example together.  
Are there any guesses on what I could be missing, in the meanwhile?

**Comment by tehhowch** [comment]
@ksubramanian2 This service does not require the `wdio/sync` module in any manner (you can see from its `package.json` that wdio/sync is not present, and also that its own plugin tests are written for the required-async future of WebdriverIO).

Please ensure you provide the version of the service that you are using, and whether the issue is present in other recent versions, too, or e.g. only the latest.

I expect the issue is related to your environment in some manner, e.g. some issue in the layers beneath the WebdriverIO abstraction. As Christian mentions, more details are necessary.

**Comment by ksubramanian2** [comment]
Thanks for the response, @tehhowch 
I copied. the dependencies' versions from this repo into my package.json now.  Below is what I have:
    "@wdio/cli":"^7.16.3",
    "@wdio/local-runner":"^7.16.3",
    "@wdio/mocha-framework":"^7.16.3",
    "@wdio/spec-reporter":"^7.16.3",
    "@wdio/static-server-service": "^7.16.3",,
    "chromedriver": "^106.0.1",
    "wdio-chromedriver-service": "^8.0.0",
    "wdio-docker-service": "3.2.0",
    "wdio-intercept-service": "^4.2.2",
    "wdio-selenium-standalone-service": "~0.0.12",
    "webdriverio": "^7.16.3",

I am using only local chrome for testing - Chrome 107.  (Tried also with Selenium)
The config file is:
const { config: baseConfig } = require('./wdio.base.config');
exports.config = Object.assign(baseConfig, {
  debug: 'true',
  capabilities: [
    {
      browserName: 'chrome',
      browserVersion: '107'
    }
  ],
  services: ['intercept', 'chromedriver']
});

In the file where I do 'browser.getRequests()', I do not have any special imports for this. 
Anything more needed?
If the issue  cannot be identified  from the above , I will create a reproduction repo.

**Comment by christian-bromann** [comment]
> Anything more needed?
> If the issue cannot be identified from the above , I will create a reproduction repo.

A reproduction repo would be the best here.

**Comment by ksubramanian2** [comment]
@christian-bromann,  I tried to create a repo  [here](https://github.com/ksubramanian2/intercepttest)
It does not reproduce the hanging situation yet.
It has the getRequests() call that works but comes back with a zero count for network requests. 
I would need your help even in fixing this before I can work on it further on the original issue of hanging.
It is a simple test, like the sample one you have.  Appreciate your help.  Thanks.

**Comment by ksubramanian2** [comment]
@christian-bromann, I have recreated the situation in this repo [here](https://github.com/ksubramanian2/intercepttest)
Can you please hep?

**Comment by ksubramanian2** [comment]
@christian-bromann, I have recreated the situation in this repo [here](https://github.com/ksubramanian2/intercepttest)
This is what I could observe so far.  Before the upgrades, if I performed a click, paused a few milli-secs and then call  getRequests(), I could see the network requests.  No longer the case after the upgrades.  

The reproduction repo is a simple test.  Opens Google search, enters a search text and looks for network calls.
In this there is a 'await browser,pause()' before 'await browser.getRequests()'
Without the browser.pause before it, getRequests() works but returns zero network calls - expected.  
With a pause of 1 second, it always works - returns four network calls.
With a pause of 5 seconds, getRequests()  hangs and times out.
Now , there is some dependency of getRequests() on browser.pause that is not clear to me.
Appreciate your help in looking at this.

**Comment by ksubramanian2** [comment]
Further update. 
This test works Ok in Safari without the getRequests( ) hanging.
The issue happens only in the latest Chrome v107, likely.

**Comment by ksubramanian2** [comment]
> 

Thank you.

**Comment by ksubramanian2** [comment]
@christian-bromann 
I had created the reproduction repo as requested by you.  Appreciate ay insights you can provide. 
After cloning the repo and yarn, please run 'yarn test'.  Will not take more than five minutes of your time.   Thanks.

**Comment by tehhowch** [comment]
@ksubramanian2 Do you need this line in your config?
https://github.com/ksubramanian2/intercepttest/blob/813f44b382e185d7ad4248bdacf7e296b585ca75/config.js#L31

FWIW I can run this just fine on macOS with Chrome 107, even with that `sync: true` line.

```
intercepttest (master)$ yarn test
yarn run v1.22.18
warning package.json: "test" is also the name of a node core module
$ wdio run config.js --spec test.js

Execution of 1 workers started at 2022-11-08T22:55:28.372Z

[0-0] RUNNING in chrome - /test.js
[0-0] entering getRequests
[0-0] returned from getRequests
[0-0] requests count = 3
[0-0] PASSED in chrome - /test.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 107.0.5304.87 mac os x #0-0] Running: chrome (v107.0.5304.87) on mac os x
[chrome 107.0.5304.87 mac os x #0-0] Session ID: 1a02e0434dd25d01ca867913515bae36
[chrome 107.0.5304.87 mac os x #0-0]
[chrome 107.0.5304.87 mac os x #0-0] » /test.js
[chrome 107.0.5304.87 mac os x #0-0] intercept test
[chrome 107.0.5304.87 mac os x #0-0]    ✓ getRequests test
[chrome 107.0.5304.87 mac os x #0-0]
[chrome 107.0.5304.87 mac os x #0-0] 1 passing (8.6s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:18 

✨  Done in 20.34s.
intercepttest (master)$ node --version
v16.18.1
intercepttest (master)$ yarn wdio --version
yarn run v1.22.18
warning package.json: "test" is also the name of a node core module
$ /Users/bhauch/apps/intercepttest/node_modules/.bin/wdio --version
7.25.4
✨  Done in 0.99s.
```

PS: you don't need to do arbitrary waits any more, the service provides the capability to build your own "pending request waiter" via the [`browser.hasPendingRequests()`](https://github.com/webdriverio-community/wdio-intercept-service#browserhaspendingrequests) method. My team's implementation is very simple, and alternates waiting 50 milliseconds with polling that method. Once there are no more pending requests, then the `getRequests()` call is made, ordering the requests by their start time.

**Comment by ksubramanian2** [comment]
Thanks, @tehhowch 
I will check out the has PendingRequests method. 
When I run the code, I get the following:
[0-0] RUNNING in chrome - /test.js
[0-0] entering getRequests
[0-0] Error in "intercept test.getRequests test"
Error: Timeout of 20000ms exceeded. The execution in the test "intercept test getRequests test" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/ksubramanian3/Documents/projects/intercepttest/test.js)
    at createTimeoutError (/Users/ksubramanian3/Documents/projects/intercepttest/node_modules/mocha/lib/errors.js:498:15)
    at Test.Runnable._timeoutError (/Users/ksubramanian3/Documents/projects/intercepttest/node_modules/mocha/lib/runnable.js:431:10)

Sometimes, I get:
Execution of 1 workers started at 2022-11-08T23:14:19.517Z

[0-0] RUNNING in chrome - /test.js
[0-0] entering getRequests
[0-0] 2022-11-08T23:14:40.109Z ERROR webdriver: Request failed with status 404 due to no such window: no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: chrome=107.0.5304.87)
[0-0] no such window in "intercept test.getRequests test"
no such window: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=107.0.5304.87)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getRequest (/Users/ksubramanian3/Documents/projects/intercepttest/node_modules/wdio-intercept-service/index.js:281:23)

**Comment by ksubramanian2** [comment]
@tehhowch 
I used this sequence instead of duration waits. 
        await browser.hasPendingRequests();
        const requests = await browser.getRequests({includePending: true});
It works more consistently.  Thanks.
Then when I examine each of the requests and its response.statusCode, the response area is not available.
Is there a wait I can do for the request to complete?
This is not very critical for our application, but it is something we used to do.
