### ISSUE TITLE
Intercepting segmentio messages

### ISSUE THREAD

**Issue by ksubramanian2** [webdriverio-community/wdio-intercept-service#467]
I have been using the intercept service to intercept segmentio messages.
We have now upgraded to their new https://github.com/segmentio/analytics-next library.
Ever since, we are not able to see any of their messages in getRequests().
I know the interceptor is set up right because it is showing all the other network calls.
Only the messages generated by the segmentio library do not show up.
Anything about this library https://github.com/segmentio/analytics-next that needs special handling for the interceptor?

**Comment by tehhowch** [comment]
> I have been using the intercept service to intercept segmentio messages.
> We have now upgraded to their new https://github.com/segmentio/analytics-next library.
> Ever since, we are not able to see any of their messages in getRequests().
> I know the interceptor is set up right because it is showing all the other network calls.
> Only the messages generated by the segmentio library do not show up.
> Anything about this library https://github.com/segmentio/analytics-next that needs special handling for the interceptor?
> 

Based on your description, yes. I don't know anything about that library or how it implements its tracking functionality. If you would like this service to support intercepting those requests, you will need to do some research to figure out what that library is doing differently, and why that difference doesn't play with how this library works (which is by wrapping the global `window` object's fetch and XHR).

A PR to add support for whatever that library is now doing would be welcomed.

**Comment by ksubramanian2** [comment]
Thanks, @tehhowch, for the very quick response. 
I can try creating the PR and testing it out. 
Below is some code I see in the [library](https://github.com/segmentio/analytics-next/blob/master/packages/browser/src/plugins/segmentio/fetch-dispatcher.ts)
import unfetch from 'unfetch'

let fetch = unfetch
if (typeof window !== 'undefined') {
  fetch = window.fetch || unfetch
}

export type Dispatcher = (url: string, body: object) => Promise<unknown>

export default function (): { dispatch: Dispatcher } {
  function dispatch(url: string, body: object): Promise<unknown> {
    return fetch(url, {
      headers: { 'Content-Type': 'text/plain' },
      method: 'post',
      body: JSON.stringify(body),
    })
  }

  return {
    dispatch,
  }
}
Anything stand out?

**Comment by ksubramanian2** [comment]
@tehhowch  I see the problem in the code above.
'fetch' variable is getting set at module initialization and even though the correct window.fetch (with interceptor) is passed to the analytics.page call later, dispatch is not using the current window.fetch, but uses the stored value of 'fetch'. One fix would be to make the assignment to 'fetch' inside the dispatch function. Then it would use the latest value.

**Comment by tehhowch** [comment]
There is no change possible in wdio-intercept-service, short of an entire change in its architecture (to support intercepting by some means that is not redefining `window.fetch` and global `XMLHttpRequest`), that will allow intercepting that code. You would need to propose the library revert a change it likely made for a specific reason, which is probably unlikely to be accepted.

**Comment by ksubramanian2** [comment]
@tehhowch  I have created a PR for the library to enable the intercept.
