### ISSUE TITLE
Cypress does not intercept graphql query

### ISSUE THREAD

**Issue by vadimsabadosh** [webdriverio-community/wdio-intercept-service#624]
1. Problem
// step.cy.ts
```/// <reference types="cypress" />
import { hasOperationName } from '../support/utils'
import step1Data from '../fixtures/step1.json'

describe('Step 1 Page', () => {
	beforeEach(() => {
		cy.intercept('POST', `${Cypress.env('api_url')}*`, (req) => {
			cy.log('intercept', req)

			if (hasOperationName(req, 'getUser')) {
				req.alias = 'getUser'
				req.reply((res) => {
					cy.log('getUser')
					// res.send({ fixture: 'step1.json' })
					res.body.data.registration = step1Data.registration
				})
			}
		})
		cy.visit('/step1')
	})
	it('should open page', () => {
		cy.wait('@getUser').then(() => {
			cy.get('.step__title').should('exist')
		})
	})
})
```
![image](https://github.com/webdriverio-community/wdio-intercept-service/assets/72106830/d0a22fc8-e07a-4d4a-8948-22e642c8856a)
I get the error

I have tried options from this topic [https://github.com/cypress-io/cypress/issues/25210](url)
But no result.
Also, I do not see any requests in the network tab of the browser dev tools.

2. My config

```import { defineConfig } from 'cypress'

export default defineConfig({
	video: false,
	screenshotOnRunFailure: true,
	viewportHeight: 1080,
	viewportWidth: 1920,
	retries: {
		runMode: 2,
		openMode: 1
	},
	env: {
		api_url: 'some url'
	},
	e2e: {
		baseUrl: 'http://localhost:3000'
	}
})
```
cypress version: "^12.17.3",
Ubuntu 22.10, test with chrome 115 & electron 106

Interesting thing that cypress intercepts mutations after clicking or submitting forms

**Comment by christian-bromann** [comment]
This is a WebdriverIO project which doesn't use Cypress. I recommend raising an issue in their project. Thanks!

**Comment by vadimsabadosh** [comment]
Ohh, sorry. I've just noticed that.
