### ISSUE TITLE
Issue with Intercepting Requests: Unwanted Logs for Excluded URLs

### ISSUE THREAD

**Issue by ASaiAnudeep** [webdriverio-community/wdio-intercept-service#861]
I am encountering an issue where unwanted logs appear in the console while intercepting network requests. Specifically, I am seeing repeated log entries like the following:

```
POST request to https://www.google-analytics.com ... had no response headers!
```

I have tried to exclude these URLs from interception by using the `excludeUrls` method, but the logs still persist. Here is the code snippet I used for exclusion:

```js
await browser.setupInterceptor();
await browser.excludeUrls([
  /.*google-analytics.*/,
  /.*facebook.*/,
]);
```

If there is a known issue or workaround, please let me know.

**Comment by ASaiAnudeep** [comment]
I wanted to mention that using `browser.mock` is not feasible for us because it isn't supported on BrowserStack or SauceLabs, which are critical to our testing infrastructure. This limitation is a hard blocker for our testing setup.

Is there any alternative approach or workaround that you could suggest for handling it.

Thanks in advance.

**Comment by christian-bromann** [comment]
@ASaiAnudeep in v9 the `mock` command uses WebDriver Bidi primitives which should work on Sauce Labs and BrowserStack.
